In [73]:
import pandas as pd
import pickle

#dataset_PCA_90_10.csv
#scaler_PCA_90_10.dat
#pca_PCA_90_10.dat
#ncomponents_PCA_90_10.dat

dataset_path = "./data/dataset_PCA_99_90.csv"
scaler_path = "./bin/scaler_PCA_99_90.dat"
pca_path = "./bin/pca_PCA_99_90.dat"
ncomponents_path = "./bin/ncomponents_PCA_99_90.dat"

df = pd.read_csv(dataset_path)
scaler = pickle.load(open(scaler_path, "rb"))
pca = pickle.load(open(pca_path, "rb"))
ncomponents = pickle.load(open(ncomponents_path, "rb"))

print("Completed")
df.tail(5)

Completed

,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,path
81,3.855853,-3.391244,-4.713304,-1.332690,6.952826,2.374866,-4.808444,1.729599,-0.028568,-1.504282,...,-0.108206,0.253952,0.737105,0.516636,0.071935,1.000311,-0.023063,-0.199414,0.165725,./DataSet/90/S8_2.jpg
82,2.985067,-1.481813,-4.090513,-0.700914,6.727893,3.859329,-4.242335,1.539148,-1.938745,-0.552203,...,-0.512481,-0.602065,-0.555680,0.065578,0.178379,-0.754635,0.649924,0.295846,-0.118724,./DataSet/90/S8_8.jpg
83,-4.695855,-0.964610,-2.151845,-2.898767,3.403239,-4.150336,-1.829148,-2.255537,-0.384219,1.036859,...,-0.540913,-0.041558,0.175110,-0.305080,0.223106,-0.505514,1.005414,-0.154155,-0.429530,./DataSet/90/S9_2.jpg
84,-4.965034,-1.095409,-2.182566,-3.971733,3.720411,-2.971209,-2.613664,-1.248816,-0.338669,1.120415,...,-0.157256,-0.369601,-0.116712,0.431601,-0.521571,0.137548,-0.601149,0.589525,-0.377736,./DataSet/90/S9_6.jpg
85,-4.874840,-0.817356,-0.756289,-3.900285,3.658141,-2.992822,-3.366057,-1.709706,-0.492723,0.276243,...,0.566837,0.645000,-0.375549,-0.179991,1.057232,0.406989,0.281891,-0.087689,0.183743,./DataSet/90/S9_8.jpg

In [74]:
features = [str(i) for i in range(1, ncomponents+1)]
x = df.loc[:, features]
y = df.loc[:, ["path"]]
y.tail(5)

                     path
81  ./DataSet/90/S8_2.jpg
82  ./DataSet/90/S8_8.jpg
83  ./DataSet/90/S9_2.jpg
84  ./DataSet/90/S9_6.jpg
85  ./DataSet/90/S9_8.jpg

In [75]:
import numpy as np
from rtree import index
nrows = df.shape[0]

path = "./bin_test/rtree_index_99_90"
p = index.Property()
p.dimension = ncomponents #D

idx = index.Index(path, properties=p)

for i in range(nrows):
    v = x.iloc[i].values
    image = y.iloc[i].values[0]
    point = tuple(np.concatenate([v, v]))
    idx.insert(i, point, obj=image)

idx.close()
print("rtree ready")

rtree ready